### PR TITLE
Changed defaults, added some functions

### PR DESCRIPTION
**Pull request by MightySlaytanic**

### CODE REVIEW

**Review by ponceto — COMMENTED** [review]
Don't want the tool to be interactive, so I will reject the commit

[0cb674e](https://github.com/ponceto/pve-bulk/pull/1/commits/0cb674e3b1a44b4a34a8731523ffbbad82f8a324)

**Comment by MightySlaytanic** [comment]
Ok, fine.

**Comment by ponceto** [comment]
I'm currently reviewing the code. Thank you for your contibution \o/

**Comment by ponceto** [comment]
Merged ! Thank you Gianni !

**Comment by MightySlaytanic** [comment]
Thank you for the update!

**Pull request closed without merging**
