### PR TITLE
[very low priority] Small fixed to remove some MarkDown warnings

### PR DESCRIPTION
**Pull request by MightySlaytanic**

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by ponceto** [comment]
Hi! 

angle brackets are typically used in UNIX to represent characters. In markdown it doesn't represent a link, square brackets are used for that.

But I'll update angle brackets to be inserted into backquotes for better readability

**Comment by MightySlaytanic** [comment]
I'm sorry, you're definitely right about angle brackets 🫣

**Comment by ponceto** [comment]
No worries !

**Comment by MightySlaytanic** [comment]
Ive checked better for links and angle brackets can be used to insert quick links while the square brackets are used to provide a specific name for a link that follows in round brackets ;-)

https://www.codecademy.com/resources/docs/markdown/links

**Pull request closed without merging**
