### PR TITLE
Added bash-completion script for pve-bulk

### PR DESCRIPTION
**Pull request by MightySlaytanic**
I've created a bash-completion script for pie-bulk tool along with a README.md file with some documentation. I've also updated some missing info in the pve-bulk README.md file.

### CODE REVIEW

**Comment by ponceto** [comment]
Hi Gianny!

Thank you for the bash completion contribution.

I'll review the PR this weekend 🔥

**Comment by MightySlaytanic** [comment]
I've just realized I've missed few actions to be processed along with listsnapshot, tomorrow I'll fix it.

**Comment by MightySlaytanic** [comment]
Hi @ponceto , I should have fixed the missing actions. If you like and approve it we could maybe put a link in the main README.md file to the README.md of bash-completion script.

**Comment by ponceto** [comment]
Merge (and squash) is done ! Version 1.3.0 is now tagged. 

I'll soon create a build script to create a .deb package to be easier to install

Thank you for your work !

**Pull request closed without merging**
